apiVersion: v1
kind: Service
metadata:
  name: {{ template "daedalus-ai.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "daedalus-ai.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "daedalus-ai.name" . }}
  type: "{{ .Values.service.type }}"
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
